//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("VisualizationModel", "FK_TweetHashtag_1", "Hashtag", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DB2.Hashtag), "TweetHashtag", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DB2.TweetHashtag), true)]
[assembly: EdmRelationshipAttribute("VisualizationModel", "FK_Media_0", "Website", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DB2.Website), "Medium", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DB2.Medium), true)]
[assembly: EdmRelationshipAttribute("VisualizationModel", "FK_TweetHashtag_0", "Tweet", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DB2.Tweet), "TweetHashtag", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DB2.TweetHashtag), true)]
[assembly: EdmRelationshipAttribute("VisualizationModel", "FK_Website_0", "Tweet", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DB2.Tweet), "Website", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DB2.Website), true)]
[assembly: EdmRelationshipAttribute("VisualizationModel", "FK_TweetWebsite2_0", "Tweet", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DB2.Tweet), "TweetWebsite", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DB2.TweetWebsite), true)]
[assembly: EdmRelationshipAttribute("VisualizationModel", "FK_TweetWebsite2_1", "Website", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DB2.Website), "TweetWebsite", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DB2.TweetWebsite), true)]

#endregion

namespace DB2
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class VisualizationEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new VisualizationEntities object using the connection string found in the 'VisualizationEntities' section of the application configuration file.
        /// </summary>
        public VisualizationEntities() : base("name=VisualizationEntities", "VisualizationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VisualizationEntities object.
        /// </summary>
        public VisualizationEntities(string connectionString) : base(connectionString, "VisualizationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VisualizationEntities object.
        /// </summary>
        public VisualizationEntities(EntityConnection connection) : base(connection, "VisualizationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Hashtag> Hashtags
        {
            get
            {
                if ((_Hashtags == null))
                {
                    _Hashtags = base.CreateObjectSet<Hashtag>("Hashtags");
                }
                return _Hashtags;
            }
        }
        private ObjectSet<Hashtag> _Hashtags;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Medium> Media
        {
            get
            {
                if ((_Media == null))
                {
                    _Media = base.CreateObjectSet<Medium>("Media");
                }
                return _Media;
            }
        }
        private ObjectSet<Medium> _Media;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tweet> Tweets
        {
            get
            {
                if ((_Tweets == null))
                {
                    _Tweets = base.CreateObjectSet<Tweet>("Tweets");
                }
                return _Tweets;
            }
        }
        private ObjectSet<Tweet> _Tweets;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TweetHashtag> TweetHashtags
        {
            get
            {
                if ((_TweetHashtags == null))
                {
                    _TweetHashtags = base.CreateObjectSet<TweetHashtag>("TweetHashtags");
                }
                return _TweetHashtags;
            }
        }
        private ObjectSet<TweetHashtag> _TweetHashtags;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Website> Websites
        {
            get
            {
                if ((_Websites == null))
                {
                    _Websites = base.CreateObjectSet<Website>("Websites");
                }
                return _Websites;
            }
        }
        private ObjectSet<Website> _Websites;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TweetWebsite> TweetWebsites
        {
            get
            {
                if ((_TweetWebsites == null))
                {
                    _TweetWebsites = base.CreateObjectSet<TweetWebsite>("TweetWebsites");
                }
                return _TweetWebsites;
            }
        }
        private ObjectSet<TweetWebsite> _TweetWebsites;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Hashtags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHashtags(Hashtag hashtag)
        {
            base.AddObject("Hashtags", hashtag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Media EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMedia(Medium medium)
        {
            base.AddObject("Media", medium);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tweets EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTweets(Tweet tweet)
        {
            base.AddObject("Tweets", tweet);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TweetHashtags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTweetHashtags(TweetHashtag tweetHashtag)
        {
            base.AddObject("TweetHashtags", tweetHashtag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Websites EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWebsites(Website website)
        {
            base.AddObject("Websites", website);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TweetWebsites EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTweetWebsites(TweetWebsite tweetWebsite)
        {
            base.AddObject("TweetWebsites", tweetWebsite);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VisualizationModel", Name="Hashtag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Hashtag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Hashtag object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="tag">Initial value of the Tag property.</param>
        public static Hashtag CreateHashtag(global::System.Int32 id, global::System.String tag)
        {
            Hashtag hashtag = new Hashtag();
            hashtag.ID = id;
            hashtag.Tag = tag;
            return hashtag;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tag
        {
            get
            {
                return _Tag;
            }
            set
            {
                OnTagChanging(value);
                ReportPropertyChanging("Tag");
                _Tag = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Tag");
                OnTagChanged();
            }
        }
        private global::System.String _Tag;
        partial void OnTagChanging(global::System.String value);
        partial void OnTagChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VisualizationModel", "FK_TweetHashtag_1", "TweetHashtag")]
        public EntityCollection<TweetHashtag> TweetHashtags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TweetHashtag>("VisualizationModel.FK_TweetHashtag_1", "TweetHashtag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TweetHashtag>("VisualizationModel.FK_TweetHashtag_1", "TweetHashtag", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VisualizationModel", Name="Medium")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Medium : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Medium object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="url">Initial value of the Url property.</param>
        /// <param name="sourceSiteID">Initial value of the SourceSiteID property.</param>
        public static Medium CreateMedium(global::System.Int32 id, global::System.String url, global::System.Int32 sourceSiteID)
        {
            Medium medium = new Medium();
            medium.ID = id;
            medium.Url = url;
            medium.SourceSiteID = sourceSiteID;
            return medium;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SourceSiteID
        {
            get
            {
                return _SourceSiteID;
            }
            set
            {
                OnSourceSiteIDChanging(value);
                ReportPropertyChanging("SourceSiteID");
                _SourceSiteID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SourceSiteID");
                OnSourceSiteIDChanged();
            }
        }
        private global::System.Int32 _SourceSiteID;
        partial void OnSourceSiteIDChanging(global::System.Int32 value);
        partial void OnSourceSiteIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Width
        {
            get
            {
                return _Width;
            }
            set
            {
                OnWidthChanging(value);
                ReportPropertyChanging("Width");
                _Width = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Width");
                OnWidthChanged();
            }
        }
        private Nullable<global::System.Int32> _Width;
        partial void OnWidthChanging(Nullable<global::System.Int32> value);
        partial void OnWidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Height
        {
            get
            {
                return _Height;
            }
            set
            {
                OnHeightChanging(value);
                ReportPropertyChanging("Height");
                _Height = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Height");
                OnHeightChanged();
            }
        }
        private Nullable<global::System.Int32> _Height;
        partial void OnHeightChanging(Nullable<global::System.Int32> value);
        partial void OnHeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VisualizationModel", "FK_Media_0", "Website")]
        public Website Website
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Website>("VisualizationModel.FK_Media_0", "Website").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Website>("VisualizationModel.FK_Media_0", "Website").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Website> WebsiteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Website>("VisualizationModel.FK_Media_0", "Website");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Website>("VisualizationModel.FK_Media_0", "Website", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VisualizationModel", Name="Tweet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tweet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tweet object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="tweetID">Initial value of the TweetID property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="tweetText">Initial value of the TweetText property.</param>
        public static Tweet CreateTweet(global::System.Int32 id, global::System.String tweetID, global::System.DateTime date, global::System.String username, global::System.String tweetText)
        {
            Tweet tweet = new Tweet();
            tweet.ID = id;
            tweet.TweetID = tweetID;
            tweet.Date = date;
            tweet.Username = username;
            tweet.TweetText = tweetText;
            return tweet;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TweetID
        {
            get
            {
                return _TweetID;
            }
            set
            {
                OnTweetIDChanging(value);
                ReportPropertyChanging("TweetID");
                _TweetID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TweetID");
                OnTweetIDChanged();
            }
        }
        private global::System.String _TweetID;
        partial void OnTweetIDChanging(global::System.String value);
        partial void OnTweetIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TweetText
        {
            get
            {
                return _TweetText;
            }
            set
            {
                OnTweetTextChanging(value);
                ReportPropertyChanging("TweetText");
                _TweetText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TweetText");
                OnTweetTextChanged();
            }
        }
        private global::System.String _TweetText;
        partial void OnTweetTextChanging(global::System.String value);
        partial void OnTweetTextChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VisualizationModel", "FK_TweetHashtag_0", "TweetHashtag")]
        public EntityCollection<TweetHashtag> TweetHashtags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TweetHashtag>("VisualizationModel.FK_TweetHashtag_0", "TweetHashtag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TweetHashtag>("VisualizationModel.FK_TweetHashtag_0", "TweetHashtag", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VisualizationModel", "FK_Website_0", "Website")]
        public EntityCollection<Website> Websites
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Website>("VisualizationModel.FK_Website_0", "Website");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Website>("VisualizationModel.FK_Website_0", "Website", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VisualizationModel", "FK_TweetWebsite2_0", "TweetWebsite")]
        public EntityCollection<TweetWebsite> TweetWebsites
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TweetWebsite>("VisualizationModel.FK_TweetWebsite2_0", "TweetWebsite");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TweetWebsite>("VisualizationModel.FK_TweetWebsite2_0", "TweetWebsite", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VisualizationModel", Name="TweetHashtag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TweetHashtag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TweetHashtag object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="tweetID">Initial value of the TweetID property.</param>
        /// <param name="hashtagID">Initial value of the HashtagID property.</param>
        public static TweetHashtag CreateTweetHashtag(global::System.Int32 id, global::System.Int32 tweetID, global::System.Int32 hashtagID)
        {
            TweetHashtag tweetHashtag = new TweetHashtag();
            tweetHashtag.ID = id;
            tweetHashtag.TweetID = tweetID;
            tweetHashtag.HashtagID = hashtagID;
            return tweetHashtag;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TweetID
        {
            get
            {
                return _TweetID;
            }
            set
            {
                OnTweetIDChanging(value);
                ReportPropertyChanging("TweetID");
                _TweetID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TweetID");
                OnTweetIDChanged();
            }
        }
        private global::System.Int32 _TweetID;
        partial void OnTweetIDChanging(global::System.Int32 value);
        partial void OnTweetIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HashtagID
        {
            get
            {
                return _HashtagID;
            }
            set
            {
                OnHashtagIDChanging(value);
                ReportPropertyChanging("HashtagID");
                _HashtagID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HashtagID");
                OnHashtagIDChanged();
            }
        }
        private global::System.Int32 _HashtagID;
        partial void OnHashtagIDChanging(global::System.Int32 value);
        partial void OnHashtagIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VisualizationModel", "FK_TweetHashtag_1", "Hashtag")]
        public Hashtag Hashtag
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Hashtag>("VisualizationModel.FK_TweetHashtag_1", "Hashtag").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Hashtag>("VisualizationModel.FK_TweetHashtag_1", "Hashtag").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Hashtag> HashtagReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Hashtag>("VisualizationModel.FK_TweetHashtag_1", "Hashtag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Hashtag>("VisualizationModel.FK_TweetHashtag_1", "Hashtag", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VisualizationModel", "FK_TweetHashtag_0", "Tweet")]
        public Tweet Tweet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tweet>("VisualizationModel.FK_TweetHashtag_0", "Tweet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tweet>("VisualizationModel.FK_TweetHashtag_0", "Tweet").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Tweet> TweetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tweet>("VisualizationModel.FK_TweetHashtag_0", "Tweet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Tweet>("VisualizationModel.FK_TweetHashtag_0", "Tweet", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VisualizationModel", Name="TweetWebsite")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TweetWebsite : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TweetWebsite object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="tweetID">Initial value of the TweetID property.</param>
        /// <param name="websiteID">Initial value of the WebsiteID property.</param>
        public static TweetWebsite CreateTweetWebsite(global::System.Int32 id, global::System.Int32 tweetID, global::System.Int32 websiteID)
        {
            TweetWebsite tweetWebsite = new TweetWebsite();
            tweetWebsite.ID = id;
            tweetWebsite.TweetID = tweetID;
            tweetWebsite.WebsiteID = websiteID;
            return tweetWebsite;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TweetID
        {
            get
            {
                return _TweetID;
            }
            set
            {
                OnTweetIDChanging(value);
                ReportPropertyChanging("TweetID");
                _TweetID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TweetID");
                OnTweetIDChanged();
            }
        }
        private global::System.Int32 _TweetID;
        partial void OnTweetIDChanging(global::System.Int32 value);
        partial void OnTweetIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WebsiteID
        {
            get
            {
                return _WebsiteID;
            }
            set
            {
                OnWebsiteIDChanging(value);
                ReportPropertyChanging("WebsiteID");
                _WebsiteID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WebsiteID");
                OnWebsiteIDChanged();
            }
        }
        private global::System.Int32 _WebsiteID;
        partial void OnWebsiteIDChanging(global::System.Int32 value);
        partial void OnWebsiteIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VisualizationModel", "FK_TweetWebsite2_0", "Tweet")]
        public Tweet Tweet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tweet>("VisualizationModel.FK_TweetWebsite2_0", "Tweet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tweet>("VisualizationModel.FK_TweetWebsite2_0", "Tweet").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Tweet> TweetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tweet>("VisualizationModel.FK_TweetWebsite2_0", "Tweet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Tweet>("VisualizationModel.FK_TweetWebsite2_0", "Tweet", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VisualizationModel", "FK_TweetWebsite2_1", "Website")]
        public Website Website
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Website>("VisualizationModel.FK_TweetWebsite2_1", "Website").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Website>("VisualizationModel.FK_TweetWebsite2_1", "Website").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Website> WebsiteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Website>("VisualizationModel.FK_TweetWebsite2_1", "Website");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Website>("VisualizationModel.FK_TweetWebsite2_1", "Website", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VisualizationModel", Name="Website")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Website : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Website object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="url">Initial value of the Url property.</param>
        /// <param name="hitCount">Initial value of the HitCount property.</param>
        /// <param name="tweetID">Initial value of the TweetID property.</param>
        public static Website CreateWebsite(global::System.Int32 id, global::System.String title, global::System.String url, global::System.Int32 hitCount, global::System.Int32 tweetID)
        {
            Website website = new Website();
            website.ID = id;
            website.Title = title;
            website.Url = url;
            website.HitCount = hitCount;
            website.TweetID = tweetID;
            return website;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HitCount
        {
            get
            {
                return _HitCount;
            }
            set
            {
                OnHitCountChanging(value);
                ReportPropertyChanging("HitCount");
                _HitCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HitCount");
                OnHitCountChanged();
            }
        }
        private global::System.Int32 _HitCount;
        partial void OnHitCountChanging(global::System.Int32 value);
        partial void OnHitCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TweetID
        {
            get
            {
                return _TweetID;
            }
            set
            {
                OnTweetIDChanging(value);
                ReportPropertyChanging("TweetID");
                _TweetID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TweetID");
                OnTweetIDChanged();
            }
        }
        private global::System.Int32 _TweetID;
        partial void OnTweetIDChanging(global::System.Int32 value);
        partial void OnTweetIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LongUrlTitle
        {
            get
            {
                return _LongUrlTitle;
            }
            set
            {
                OnLongUrlTitleChanging(value);
                ReportPropertyChanging("LongUrlTitle");
                _LongUrlTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LongUrlTitle");
                OnLongUrlTitleChanged();
            }
        }
        private global::System.String _LongUrlTitle;
        partial void OnLongUrlTitleChanging(global::System.String value);
        partial void OnLongUrlTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VisualizationModel", "FK_Media_0", "Medium")]
        public EntityCollection<Medium> Media
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Medium>("VisualizationModel.FK_Media_0", "Medium");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Medium>("VisualizationModel.FK_Media_0", "Medium", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VisualizationModel", "FK_Website_0", "Tweet")]
        public Tweet Tweet
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tweet>("VisualizationModel.FK_Website_0", "Tweet").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tweet>("VisualizationModel.FK_Website_0", "Tweet").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Tweet> TweetReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Tweet>("VisualizationModel.FK_Website_0", "Tweet");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Tweet>("VisualizationModel.FK_Website_0", "Tweet", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("VisualizationModel", "FK_TweetWebsite2_1", "TweetWebsite")]
        public EntityCollection<TweetWebsite> TweetWebsites
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TweetWebsite>("VisualizationModel.FK_TweetWebsite2_1", "TweetWebsite");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TweetWebsite>("VisualizationModel.FK_TweetWebsite2_1", "TweetWebsite", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
